from enum import Enum
class ConflictType(str, Enum):
    OWNER_CONFLICT = "OWNER_CONFLICT"
    ADDRESS_CONFLICT = "ADDRESS_CONFLICT"
    PARCEL_CONFLICT = "PARCEL_CONFLICT"
    LEGAL_DESCRIPTION_CONFLICT = "LEGAL_DESCRIPTION_CONFLICT"
    APPRAISAL_CONFLICT = "APPRAISAL_CONFLICT"
    LAND_VALUE_CONFLICT = "LAND_VALUE_CONFLICT"
    IMPROVEMENT_VALUE_CONFLICT = "IMPROVEMENT_VALUE_CONFLICT"
    EXEMPTION_CONFLICT = "EXEMPTION_CONFLICT"
    YEAR_BUILT_CONFLICT = "YEAR_BUILT_CONFLICT"
    BUILDING_SIZE_CONFLICT = "BUILDING_SIZE_CONFLICT"
    UNKNOWN_CONFLICT = "UNKNOWN_CONFLICT"
class ConflictStatus(str, Enum):
    OPEN = "OPEN"
    REVIEWED = "REVIEWED"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"
