from enum import Enum
class PolicyVerdict(str, Enum):
    AUTHORIZED = "AUTHORIZED"
    DENIED = "DENIED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    EXPORT_APPROVED = "EXPORT_APPROVED"
    EXPORT_DENIED = "EXPORT_DENIED"
class PolicyReason(str, Enum):
    DECISION_ALLOWED = "DECISION_ALLOWED"
    DECISION_NOT_ALLOWED = "DECISION_NOT_ALLOWED"
    MANUAL_REVIEW_NEEDED = "MANUAL_REVIEW_NEEDED"
    EXPORT_REQUIREMENTS_MET = "EXPORT_REQUIREMENTS_MET"
    EXPORT_REQUIREMENTS_NOT_MET = "EXPORT_REQUIREMENTS_NOT_MET"
    POLICY_RULE_VIOLATED = "POLICY_RULE_VIOLATED"
