from enum import Enum
class DecisionState(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    PENDING_MORE_EVIDENCE = "PENDING_MORE_EVIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICT_RESOLUTION_REQUIRED = "CONFLICT_RESOLUTION_REQUIRED"
    READY_FOR_EXPORT = "READY_FOR_EXPORT"
class DecisionReason(str, Enum):
    NO_CONFLICTS_SUFFICIENT_EVIDENCE = "NO_CONFLICTS_SUFFICIENT_EVIDENCE"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    SINGLE_SOURCE_ONLY = "SINGLE_SOURCE_ONLY"
    MISSING_REQUIRED_EVIDENCE = "MISSING_REQUIRED_EVIDENCE"
    ACTIVE_CONFLICTS_PRESENT = "ACTIVE_CONFLICTS_PRESENT"
    EXPORT_REQUIREMENTS_MET = "EXPORT_REQUIREMENTS_MET"
