from enum import Enum
class LegalClassification(str, Enum):
    PUBLIC_RECORD = "PUBLIC_RECORD"
    PUBLIC_API = "PUBLIC_API"
    LICENSED = "LICENSED"
    LICENSED_REGULATED = "LICENSED_REGULATED"
    RESTRICTED = "RESTRICTED"
    USER_PROVIDED = "USER_PROVIDED"
class ConnectorStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    SUSPENDED = "SUSPENDED"
    DRAFT = "DRAFT"
class ConnectorCategory(str, Enum):
    COUNTY_PUBLIC_RECORDS = "COUNTY_PUBLIC_RECORDS"
    GIS = "GIS"
    FLOOD = "FLOOD"
    WEATHER = "WEATHER"
    MARKET = "MARKET"
    USER_DOCUMENTS = "USER_DOCUMENTS"
ALLOWED_CAPABILITIES = {
    "OWNERSHIP",
    "PARCEL",
    "TAX_ASSESSMENT",
    "BUILDING_SIZE",
    "LOT_SIZE",
    "YEAR_BUILT",
    "LEGAL_DESCRIPTION",
    "FLOOD_ZONE",
    "WEATHER_HISTORY",
    "PERMIT_HISTORY",
    "USER_DOCUMENT",
}
